### ISSUE TITLE
smart-on-fhir/api-server: URL "Sample Patients:" points to old sample data project

### ISSUE THREAD

**Issue by ascooper57** [smart-on-fhir/api-server#35]
https://github.com/smart-on-fhir/api-server

URL "Sample Patients:" point to https://github.com/chb/smart_sample_patients/tree/fhir
should be https://github.com/smart-on-fhir/sample-patients
========================================
Getting more sample data

You can load sample data from SMART's Sample Patients:

$ sudo apt-get install python-jinja2
$ git clone --recursive https://github.com/smart-on-fhir/sample-patients
$ cd sample-patients/bin
$ git checkout fhir
$ python generate.py --write-fhir ../generated-data
$ ls ../generated-data # a bunch of XML files

**Comment by ascooper57** [comment]
git checkout fhir under  sample-patients/bin fails as well
$ cd sample-patients/bin
$ git checkout fhir

**Comment by ascooper57** [comment]
The "old" project says to use "../test-data". Going forward, it should be generated-data especially since it has a .gitignore file to filter out all of the generated files as the new project has it defined: https://github.com/smart-on-fhir/sample-patients

**Comment by jmandel** [comment]
Thanks -- updated with https://github.com/smart-on-fhir/api-server/commit/603f2038880ed06777f221a410cc93dbb79c3043
