### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by pvyaka01** [smart-on-fhir/api-server#38]
•Turn authentication or off with  fhir.oauth.enabled :  true | false 

Where do we pass this flag or add this flag? I tried to pass it on the command line as:

./grailsw run-app --fhir-oauth.enabled:false

That did not work and got an error about oauth not being setup. 

Thanks!

**Comment by jmandel** [comment]
This is a setting in config.groovy, at https://github.com/smart-on-fhir/api-server/blob/master/grails-app/conf/Config.groovy#L115

If you want to pass an external flag you can do so by setting a shell variable called `AUTH`. E.g. in linux you could run:

    AUTH=false ./grailsw run-app
