### ISSUE TITLE
POST example

### ISSUE THREAD

**Issue by pvyaka01** [smart-on-fhir/api-server#39]
Josh, 
I got the server running. However, when I try to POST Patient-example.xml with command:

 curl 'h0/DiagnosticOrder/example' -X PUT -H 'Authorization: Basic Y2xpZW50OnNlY3JldA=='-H 'Content-Type: text/xml' --data @grails-app/conf/examples/Patient-example.xml

I get this message:
Warning: Couldn't read data from file
Warning: "grails-app/conf/examples/Patient-example.xml", this makes an empty
Warning: POST.
<?xml version="1.0" encoding="UTF-8"?>

<OperationOutcome xmlns="http://hl7.org/fhir">
  <issue>
    <severity value="error"/>
    <details>
      <text value="Stream closed"/>
    </details>
  </issue>
curl: (6) Couldn't resolve host 'Content-Type: text'

On the server side, I see this:
Evaluating request org.apache.catalina.core.ApplicationHttpRequest@f62d719 with null
Formats: xml + xml
errors.GrailsExceptionResolver IOException occurred when processing request: [PUT] /DiagnosticOrder/example
Stream closed. Stacktrace follows:
java.io.IOException: Stream closed
        at fhir.ApiController.parseResourceFromRequest(ApiController.groovy:131)
        at fhir.ApiController.update(ApiController.groovy:149)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
fhir.ErrorController Rendering a 500 error
fhir.ResponseFilters rendered after: 14

Any pointers? Thank you for the help!

**Comment by jmandel** [comment]
First off, the example file is a C-CDA,  so you shouldn't try to create a DiagnosticOrder from it. What specifically do you want to accomplish? 

As for the error though, curl simply isn't seeing that example fild. What directory are you running it from? What do you see when you 

    grails-app/conf/examples/Patient-example.xml

**Comment by pvyaka01** [comment]
Here's our goal:

 

Setup the API and validate that it works with the xml and the sample data
provided. Then, we want to modify the code to use our database to serve up
the data.

 

The server comes up on port 8080, I loaded up sample patient data that you
provided. I then started using the REST calls with curl per the notes on
github notes and that's when I got these errors that I mentioned. I am not
sure if there's a certain sequence that we need to follow or if I'm
completely off the mark (which could be the case here).

 

I am running everything from /api-server folder. There is data in the xml
files including patient-example.xml. 

 

Appreciate your help!

 

Thanks,

Prakash

**Comment by jmandel** [comment]
It sounds like what you probably want to do is load our structure sample
patient data -- specially, the instructions in our README under the heading
"Getting more sample data". Have you given this a shot?

**Comment by pvyaka01** [comment]
Yes, I already did that! :)
~/api-server/sample-patients/bin# python generate.py --summary 613876
613876  1965-02-13      male    Hill, Joshua
PROBLEMS:  Hypothyroidism;  Malaise and fatigue;  Arthralgia of the lower leg;  Disorder of bone and articular cartilage;  Nonspecific abnormal findings on radiological and other examination of musculoskeletal system;  Overexertion and strenuous movements;  Streptococcal sore throat;  Localized, primary osteoarthritis of the lower leg;
MEDICATIONS:  None
LABS:  None

So, the python scripts get me the patient data. Now, when I installed the api, we created fhir database in PostgreSQL. However, I do not see any tables generated by the install scripts there. Should I? Is that part of the reason for the API not returning any data?

**Comment by jmandel** [comment]
So it sounds like you have follow the steps for generating the sample data. Did that you then follow the instructions for loading those data, under "Loading these files into your system"? What output did you see?

**Comment by pvyaka01** [comment]
Josh, entries like this:
 insert into resource_index_term (id, version_id, class, fhir_type, fhir_id, search_param, date_min, date_max) values (nextval('seq_resource_version'), 180568, ResourceIndexDate, List, 63, _lastUpdated, 2015-12-07 22:57:58.62, 2015-12-07 22:57:58.62);
 insert into resource_index_term (id, version_id, class, fhir_type, fhir_id, search_param) values (nextval('seq_resource_version'), 180568, ResourceIndexString, List, 63, _profile);
fhir.SqlService Created version: http://localhost:9080/List/63/_history/180568
fhir.ApiController Transacting on an entry with Practitioner / 1234
fhir.SqlService Authorizing compartments start from: []
fhir.SqlService Updating to version id: 1234 /_history/ 180578
fhir.SqlService raw {"resourceType":"Practitioner","id":"1234","meta":{"versionId":"180578","lastUpdated":"2015-12-07T22:57:58.641-06:00"},"text":{"status":"generated","div":"<div>Practitioner: John Smith</div>"},"name":{"use":"usual","family":["Smith"],"given":["John"]}}
fhir.SqlService Parsed a Practitioner


So, sorry, yeah, I do see the that there are 5 tables in fhir db. A select:
SELECT version_id, content, fhir_id, fhir_type, rest_date, rest_operation
  FROM resource_version;

returns about 16666 rows.

Now, when I call the API, is it supposed to go against this db? So, I should be able to call it like:
http://localhost:8080/Patient?ID=   or something like that based on HL7 standard, right?

**Comment by jmandel** [comment]
16k rows looks about right. Now try something like

GET /Patient?
GET /Patient?name=amy

Note that "ID" (from your example) is not a valid search parameter.

Best,

  Josh

**Comment by pvyaka01** [comment]
Will try and let you know. Thanks!

Sent from my Cyanogen phone

On Dec 8, 2015 10:32 AM, Josh Mandel <notifications@github.com> wrote:

16k rows looks about right. Now try something like

GET /Patient?
GET /Patient?name=amy

Note that "ID" (from your example) is not a valid search parameter.

Best,

Josh

**Comment by pvyaka01** [comment]
sorry, didn't get a chance to try that till today. Yeah, http://localhost:8080/Patient?name=amy worked. Thanks!

**Comment by jmandel** [comment]
Great! Thanks for the feedback.
