### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by romanga** [smart-on-fhir/api-server#48]

**Comment by jmandel** [comment]
It is not. @gotdan it would be good to clarify in the README, and to link out to the new projects that have replaced this API server.

**Comment by romanga** [comment]
can you please point me to the new project?

**Comment by gotdan** [comment]
There's a list of open source FHIR servers here: http://wiki.hl7.org/index.php?title=Open_Source_FHIR_implementations
